insert into store(store_id, store_name, thumb1, thumb2, thumb3, min_order_price, delivery_fee, estimated_del_time, category) values (1, "BBQ-매탄점", "1_1", "1_2", "1_3", 18000, 2000, "55~65분", "치킨");
insert into store(store_id, store_name, thumb1, thumb2, thumb3, min_order_price, delivery_fee, estimated_del_time, category) values (2, "후라이드참잘하는집-인계매탄점", "2_1", "2_2", "2_3", 14000, 1500, "45~55분", "치킨");
insert into store(store_id, store_name, thumb1, thumb2, thumb3, min_order_price, delivery_fee, estimated_del_time, category) values (3, "처갓집양념치킨-권선점", "3_1", "3_2", "3_3", 14000, 3000, "45~55분", "치킨");
insert into store(store_id, store_name, thumb1, thumb2, thumb3, min_order_price, delivery_fee, estimated_del_time, category) values (4, "BHC-수원지동점", "4_1", "4_2", "4_3", 15000, 2000, "50~60분", "치킨");
insert into store(store_id, store_name, thumb1, thumb2, thumb3, min_order_price, delivery_fee, estimated_del_time, category) values (5, "멕시카나-우만점", "5_1", "5_2", "5_3", 16000, 2000, "50~60분", "치킨");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (6, "네네치킨-인계중앙점", 15000, 3000, "50~60분", "치킨");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (7, "또래오래-수원권선점", 15000, 2000, "35~45분", "치킨");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (8, "호식이두마리치킨-매탄1호점", 13000, 2000, "45~55분", "치킨");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (9, "페리카나-우만지동점", 14000, 2000, "30~40분", "치킨");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (10, "교촌치킨-인계점", 15000, 2000, "55~65분", "치킨");

insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (11, "피자브라더스-권선점", 12900, 0, "45~55분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (12, "반올림피자샵-수원점", 14900, 0, "45~55분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (13, "업텐브로피자-수원점", 10000, 0, "35~45분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (14, "왕손피자-매탄인계점", 14000, 900, "60~70분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (15, "강스피자since2000", 23900, 3800, "35~45분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (16, "뽕뜨락피자-권선점", 20000, 2500, "50~60분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (17, "올레피자24시", 15000, 2000, "50~60분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (18, "네오피자-수원1호점", 14000, 0, "45~55분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (19, "미스터피자-아주대점", 16000, 0, "35~45분", "피자");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (20, "파파존스피자-매탄점", 20000, 0, "35~45분", "피자");

insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (21, "짜마", 10000, 1000, "65~75분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (22, "소호객잔", 10000, 1000, "25~35분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (23, "시온성", 12000, 1000, "20~30분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (24, "짬뽕지존-인계점", 7000, 4000, "45~55분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (25, "홍콩반점0410-수원인계점", 13000, 2500, "55~65분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (26, "백세교동짬뽕", 16000, 2000, "50~60분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (27, "짬뽕이조아-우만점", 10000, 1000, "35~45분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (28, "미스핫마라탕", 16000, 2500, "50~60분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (29, "마라탕전문점소림마라-동수원점", 13000, 2000, "65~75분", "중식");
insert into store(store_id, store_name, min_order_price, delivery_fee, estimated_del_time, category) values (30, "1인분배달8000원마라탕천화쿵푸", 8000, 3500, "50~60분", "중식");